# Generated by Django 5.1.1 on 2024-09-08 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_login', models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='Логин почты')),
                ('mail_password', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Пароль почты')),
                ('user', models.OneToOneField(blank=True, default=None, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
