# Generated by Django 5.1.1 on 2024-09-08 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Тема')),
                ('date_send', models.DateTimeField(blank=True, db_index=True, max_length=100, verbose_name='Дата отправки ')),
                ('date_added', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата получения')),
                ('text', models.TextField(blank=True, db_index=True, default=None, null=True, verbose_name='Текст')),
            ],
        ),
    ]
